[phases.setup]
nixPkgs = ['maven', 'nodejs', 'jdk17']

[phases.build]
cmds = [
  'cd frontend && npm install && npm run build',
  'cd backend && mvn clean package -DskipTests'
]

[start]
cmd = 'cd backend && java -Dserver.port=$PORT -jar target/*.jar'
